//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.11 at 12:03:05 PM PDT 
//

package com.mitchell.examples.claim;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for LossInfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LossInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CauseOfLoss" type="{http://www.mitchell.com/examples/claim}CauseOfLossCode" minOccurs="0"/>
 *         &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LossDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LossInfoType", propOrder = { "causeOfLoss", "reportedDate",
		"lossDescription" })
@Entity
@Table(name = "LOSS_INFO_TYPE")
public class LossInfoType {

	@XmlTransient
	private BigDecimal id;
	@XmlElement(name = "CauseOfLoss")
	@XmlSchemaType(name = "string")
	protected CauseOfLossCode causeOfLoss;
	@XmlElement(name = "ReportedDate")
	@XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter(Adapter1.class)
	protected Date reportedDate;
	@XmlElement(name = "LossDescription")
	protected String lossDescription;

	public LossInfoType() {

	}

	public LossInfoType(BigDecimal id, CauseOfLossCode causeOfLoss,
			Date reportedDate, String lossDescription) {
		super();
		this.id = id;
		this.causeOfLoss = causeOfLoss;
		this.reportedDate = reportedDate;
		this.lossDescription = lossDescription;
	}

	/**
	 * Gets the value of the causeOfLoss property.
	 * 
	 * @return possible object is {@link CauseOfLossCode }
	 * 
	 */
	@Basic
	@Column(name = "CAUSE_OF_LOSS", length = 255)
	@Enumerated(EnumType.STRING)
	public CauseOfLossCode getCauseOfLoss() {
		return causeOfLoss;
	}

	/**
	 * Sets the value of the causeOfLoss property.
	 * 
	 * @param value
	 *            allowed object is {@link CauseOfLossCode }
	 * 
	 */
	public void setCauseOfLoss(CauseOfLossCode value) {
		this.causeOfLoss = value;
	}

	/**
	 * Gets the value of the reportedDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	@Basic
	@Column(name = "REPORTED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getReportedDate() {
		return reportedDate;
	}

	/**
	 * Sets the value of the reportedDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setReportedDate(Date value) {
		this.reportedDate = value;
	}

	/**
	 * Gets the value of the lossDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "LOSS_DESCRIPTION", length = 1020)
	public String getLossDescription() {
		return lossDescription;
	}

	/**
	 * Sets the value of the lossDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLossDescription(String value) {
		this.lossDescription = value;
	}

	@Id
	@SequenceGenerator(name = "lossInfoTypeSeq", sequenceName = "LOSS_INFO_TYPE_SEQ",
	allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "lossInfoTypeSeq")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
