//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.11 at 12:03:05 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mitchell.com/examples/claim", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns={@javax.xml.bind.annotation.XmlNs(prefix="cla", namespaceURI="http://www.mitchell.com/examples/claim")})
package com.mitchell.examples.claim;
