//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.11 at 12:03:05 PM PDT 
//

package com.mitchell.examples.claim;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.persistence.DiscriminatorColumn;

import static javax.persistence.DiscriminatorType.INTEGER;

/**
 * <p>
 * Java class for VehicleInfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModelYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MakeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModelDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EngineDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExteriorColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Vin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicPlate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicPlateState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicPlateExpDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DamageDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleInfoType", propOrder = { "modelYear",
		"makeDescription", "modelDescription", "engineDescription",
		"exteriorColor", "vin", "licPlate", "licPlateState", "licPlateExpDate",
		"damageDescription", "mileage" })
@Entity
@Table(name = "VEHICLE_INFO_TYPE")
public class VehicleInfoType {

	@XmlTransient
	private BigDecimal id;
	@XmlTransient
	private VehicleListType vehicleListType;
	@XmlElement(name = "ModelYear")
	protected int modelYear;
	@XmlElement(name = "MakeDescription")
	protected String makeDescription;
	@XmlElement(name = "ModelDescription")
	protected String modelDescription;
	@XmlElement(name = "EngineDescription")
	protected String engineDescription;
	@XmlElement(name = "ExteriorColor")
	protected String exteriorColor;
	@XmlElement(name = "Vin")
	protected String vin;
	@XmlElement(name = "LicPlate")
	protected String licPlate;
	@XmlElement(name = "LicPlateState")
	protected String licPlateState;
	@XmlElement(name = "LicPlateExpDate")
	@XmlJavaTypeAdapter(Adapter1.class)
	@XmlSchemaType(name = "date")
	protected Date licPlateExpDate;
	@XmlElement(name = "DamageDescription")
	protected String damageDescription;
	@XmlElement(name = "Mileage")
	protected Integer mileage;

	public VehicleInfoType() {

	}

	public VehicleInfoType(BigDecimal id, VehicleListType vehicleListType,
			String damageDescription, String engineDescription,
			String exteriorColor, String licPlate, Date licPlateExpDate,
			String licPlateState, String makeDescription, Integer mileage,
			String modelDescription, Integer modelYear, String vin) {
		this.id = id;
		this.vehicleListType = vehicleListType;
		this.damageDescription = damageDescription;
		this.engineDescription = engineDescription;
		this.exteriorColor = exteriorColor;
		this.licPlate = licPlate;
		this.licPlateExpDate = licPlateExpDate;
		this.licPlateState = licPlateState;
		this.makeDescription = makeDescription;
		this.mileage = mileage;
		this.modelDescription = modelDescription;
		this.modelYear = modelYear;
		this.vin = vin;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	@SequenceGenerator(name = "vehicleInfoTypeSeq", sequenceName = "VEHICLE_INFO_TYPE_SEQ", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "vehicleInfoTypeSeq")
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.PERSIST)
	@JoinColumn(name = "VEHICLE_DETAILS_VEHICLE_LIST_0")
	public VehicleListType getVehicleListType() {
		return this.vehicleListType;
	}

	public void setVehicleListType(VehicleListType vehicleListType) {
		this.vehicleListType = vehicleListType;
	}

	/**
	 * Gets the value of the modelYear property.
	 * 
	 */
	@Column(name = "MODEL_YEAR", precision = 10, scale = 0)
	public int getModelYear() {
		return modelYear;
	}

	/**
	 * Sets the value of the modelYear property.
	 * 
	 */
	public void setModelYear(int value) {
		this.modelYear = value;
	}

	/**
	 * Gets the value of the makeDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "MAKE_DESCRIPTION", length = 1020)
	public String getMakeDescription() {
		return makeDescription;
	}

	/**
	 * Sets the value of the makeDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMakeDescription(String value) {
		this.makeDescription = value;
	}

	/**
	 * Gets the value of the modelDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "MODEL_DESCRIPTION", length = 1020)
	public String getModelDescription() {
		return modelDescription;
	}

	/**
	 * Sets the value of the modelDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModelDescription(String value) {
		this.modelDescription = value;
	}

	/**
	 * Gets the value of the engineDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "ENGINE_DESCRIPTION", length = 1020)
	public String getEngineDescription() {
		return engineDescription;
	}

	/**
	 * Sets the value of the engineDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEngineDescription(String value) {
		this.engineDescription = value;
	}

	/**
	 * Gets the value of the exteriorColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "EXTERIOR_COLOR", length = 1020)
	public String getExteriorColor() {
		return exteriorColor;
	}

	/**
	 * Sets the value of the exteriorColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExteriorColor(String value) {
		this.exteriorColor = value;
	}

	/**
	 * Gets the value of the vin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVin() {
		return vin;
	}

	/**
	 * Sets the value of the vin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVin(String value) {
		this.vin = value;
	}

	/**
	 * Gets the value of the licPlate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */

	@Column(name = "LIC_PLATE", length = 1020)
	public String getLicPlate() {
		return licPlate;
	}

	/**
	 * Sets the value of the licPlate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLicPlate(String value) {
		this.licPlate = value;
	}

	/**
	 * Gets the value of the licPlateState property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "LIC_PLATE_STATE", length = 1020)
	public String getLicPlateState() {
		return licPlateState;
	}

	/**
	 * Sets the value of the licPlateState property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLicPlateState(String value) {
		this.licPlateState = value;
	}

	/**
	 * Gets the value of the licPlateExpDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "LIC_PLATE_EXP_DATE", length = 7)
	public Date getLicPlateExpDate() {
		return licPlateExpDate;
	}

	/**
	 * Sets the value of the licPlateExpDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setLicPlateExpDate(Date value) {
		this.licPlateExpDate = value;
	}

	/**
	 * Gets the value of the damageDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "DAMAGE_DESCRIPTION", length = 1020)
	public String getDamageDescription() {
		return damageDescription;
	}

	/**
	 * Sets the value of the damageDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDamageDescription(String value) {
		this.damageDescription = value;
	}

	/**
	 * Gets the value of the mileage property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	@Column(name = "MILEAGE", precision = 10, scale = 0)
	public Integer getMileage() {
		return mileage;
	}

	/**
	 * Sets the value of the mileage property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMileage(Integer value) {
		this.mileage = value;
	}

}
